# Generated by Django 5.2.8 on 2025-11-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='JanSeva', max_length=200)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('launch_date', models.CharField(max_length=100)),
                ('features', models.JSONField(default=list)),
                ('tech_stack', models.JSONField(default=dict)),
                ('collaborators', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
